### ISSUE TITLE
addnode error in bold

### ISSUE THREAD

**Issue by seatrips** [genix-project/masternode-setup-script#1]
function addnodes() {
	echo "Adding nodes..."
	conffile=/root/.genixcore/genix.conf
	**echo -e "\addnode=45.77.125.15" >> ${conffile}**
	echo -e "addnode=198.12.95.122" >> ${conffile}
	echo -e "addnode=149.28.56.171" >> ${conffile}
	echo "Done..."

**Comment by farsider350** [comment]
Fixed with commit 3b95572
